#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb  4 14:30:12 2019

@author: Ismael Bonneau & Issam Benamara
"""

with open('dataPath.txt') as f:
    lines = f.readlines()
    path = lines[0]

print(path)